# Generated by Django 2.1.2 on 2018-10-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='is_grand_user',
        ),
        migrations.RemoveField(
            model_name='street',
            name='street_type',
        ),
        migrations.DeleteModel(
            name='StreetType',
        ),
    ]
