# Generated by Django 2.0.2 on 2018-03-07 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_streettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True, verbose_name='zipcode')),
                ('is_grand_user', models.BooleanField(default=False, verbose_name='is grand user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Neighborhood', verbose_name='neighborhood')),
                ('street_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.StreetType', verbose_name='street type')),
            ],
        ),
    ]
